name: do_now
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  # ios
  image_path: "assets/images/donow_icon.png"
  remove_alpha_ios: true
  # android
  adaptive_icon_foreground: "assets/images/donow_icon.png"
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground_inset: 0

flutter_native_splash:
  color: '#FFFFFF'
  image: "assets/images/donow_icon.png"
  android: false
  ios: true