// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzQKAxQwAwttWjn1Jy9C4Uv2hhhA7Gf_8',
    appId: '1:784527243811:android:dd3a2320f9c8ad6e44cf96',
    messagingSenderId: '784527243811',
    projectId: 'do-now-app',
    storageBucket: 'do-now-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Xo_-UWUxIheiQjSaxgwFFKG815pNniY',
    appId: '1:784527243811:ios:2feedc285fff91f244cf96',
    messagingSenderId: '784527243811',
    projectId: 'do-now-app',
    storageBucket: 'do-now-app.firebasestorage.app',
    androidClientId: '784527243811-1mklf61bbv6u3p26ft48hsesasn4f8ae.apps.googleusercontent.com',
    iosClientId: '784527243811-pl623mls0eefipv9557lomj8q21gkl3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.doNow',
  );

}